#                 Explorative Data Analysis(EDA)

In [ ]:
# Clean the data - Preprocessing the data

# null values, duplicated values, check data type of your column and check the format
# stastical functins - all the different measures
# discover the insights, identify outliers, find out the correlation between diff. columns
# find patterns, create visualization, different hypothesis
# therefore make the model ready

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('/content/BBData (1) (1).csv')

In [6]:
df.shape

(27555, 10)

In [7]:
df.columns

Index(['index', 'product', 'category', 'sub_category', 'brand', 'sale_price',
       'market_price', 'type', 'rating', 'description'],
      dtype='object')

In [8]:
df.sample() # random row

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
18760,18761,Groundnut - Broken,Snacks & Branded Foods,Snacks & Namkeen,Sanjay,72.0,72.0,Namkeen & Savoury Snacks,4.0,Made with groundnet

In [9]:
df.sample(20)

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
21898,21899,Infant Nail Scissors,Baby Care,Baby Accessories,Pigeon Baby,795.00,795.00,"Combs, Brushes, Clippers",4.0,Pigeon present this amazing nail scissor for t...
1152,1153,Tango Whisky Glass Tumbler,"Kitchen, Garden & Pets",Crockery & Cutlery,Pasabahce,489.00,666.00,Glassware,2.5,These simple yet elegant-looking glasses are i...
2470,2471,San Remo Pasta 500G + Disano Olive Oil Pure 1L...,Gourmet & World Food,"Pasta, Soup & Noodles",bb Combo,1039.00,1690.00,Pastas & Spaghetti,NaN,San Remo are the pasta experts and now export ...
8316,8317,Face Wash For Acne & Pollution Control - Activ...,Beauty & Hygiene,Skin Care,Super Smelly,284.25,379.00,Face Care,3.0,When your face feels heavy under layers of dir...
3101,3102,Fresh Catch Basa Fish Portions,"Eggs, Meat & Fish",Fish & Seafood,Ifb,290.00,290.00,Frozen Fish & Seafood,NaN,At IFB FreshCatch we are committed to serving ...
6046,6047,Red Chilli Powder 200G +Coriander/Dhania Powde...,"Foodgrains, Oil & Masala",Masalas & Spices,bb Royal,112.80,240.00,Powdered Spices,NaN,"Chili powder is the dried, pulverized fruit of..."
7244,7245,"Plastic Bucket With Handle - Pink, Super Saver...",Cleaning & Household,Bins & Bathroom Ware,Ratan,199.00,313.00,Buckets & Mugs,4.0,These buckets come in a varied range and are s...
21414,21415,Dlite The Dark Collection - Assorted Chocolate...,Snacks & Branded Foods,Chocolates & Candies,Sugar free,524.25,699.00,Gift Boxes,4.3,An assorted range of chocolates crafted specia...
18898,18899,Desi A2 Gir Cow Ghee/Tuppa,"Foodgrains, Oil & Masala",Organic Staples,Praakritik,1450.00,1450.00,"Organic Edible Oil, Ghee",4.3,"Our 100% natural Desi Gir Cow A2 Ghee, is craf..."
15845,15846,Sugarfree Power Mix,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,400.00,400.00,"Healthy, Baked Snacks",NaN,This diverse mix of nuts is a great way to get...
5912,5913,Chewing Gum - Peppermint,Snacks & Branded Foods,Chocolates & Candies,Doublemint,10.00,10.00,Mints & Chewing Gum,4.2,Opportunities to connect with someone new happ...
14088,14089,Greek Yogurt - Blueberry,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",Epigamia,105.84,180.00,Flavoured & Greek Yogurt,4.0,Epigama means in Ancient Greek meant a way to ...
3075,3076,LionPride - Pocket Deodorant - 0% Gas,Beauty & Hygiene,Fragrances & Deos,Old Spice,71.25,75.00,Men's Deodorants,4.1,Smellcome to Magic with Old Spice’s New Launch...
12142,12143,Red Hot Mouthwash,Beauty & Hygiene,Oral Care,Closeup,375.00,375.00,Mouthwash,NaN,New Closeup Red Hot Mouthwash is for long-last...
25460,25461,Insta Glow Qxygen Bleach,Beauty & Hygiene,Skin Care,Vlcc,89.10,99.00,Face Care,4.3,Gold signifies purity and tranquility and has ...
13194,13195,Ash Gourd - Cut,Fruits & Vegetables,Cuts & Sprouts,Fresho,15.00,18.75,Cut & Peeled Veggies,NaN,Our uniformly and perfectly cut fresh ash gour...
10156,10157,"Steel Bowl/Vati/Katori - No. 5.5, Sada","Kitchen, Garden & Pets",Steel Utensils,BB Home,199.00,279.00,Bowls & Vessels,4.4,BB Home Sada Vatti is made from high-grade sta...
4001,4002,Sugar Less - Gulab Jamun,Snacks & Branded Foods,Ready To Cook & Eat,Dezire,185.00,185.00,"Tinned, Packed Sweets",NaN,Gulab Jamun Tin - 250 Gm For Health Watchers A...
8770,8771,Gram Flour - Besan/Kadale Hittu,"Foodgrains, Oil & Masala","Atta, Flours & Sooji",Elite,60.00,60.00,"Sooji, Maida & Besan",4.2,Gram flour or chickpea flour or besan is a pul...
27104,27105,Pickle - Prawn,Snacks & Branded Foods,Pickles & Chutney,Nirapara,95.00,95.00,Non Veg Pickle,3.4,Nirapara Prawn Pickle is an easy recipe for a ...

In [10]:
df.head()

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27555 entries, 0 to 27554
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         27555 non-null  int64
 1   product       27554 non-null  object
 2   category      27555 non-null  object
 3   sub_category  27555 non-null  object
 4   brand         27554 non-null  object
 5   sale_price    27555 non-null  float64
 6   market_price  27555 non-null  float64
 7   type          27555 non-null  object
 8   rating        18929 non-null  float64
 9   description   27440 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 2.1+ MB

In [ ]:
# check the null and duplicate values present in the data

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.isnull().sum()

index              0
product            1
category           0
sub_category       0
brand              1
sale_price         0
market_price       0
type               0
rating          8626
description      115
dtype: int64

In [14]:
df = df.dropna(subset=['product']) # dropna - drop the null values , drop the rows which are having null values

In [15]:
df.isnull().sum()

index              0
product            0
category           0
sub_category       0
brand              1
sale_price         0
market_price       0
type               0
rating          8626
description      115
dtype: int64

In [16]:
# brand column as well we are having 1 null value we can either delete it or we can fill it with some specific value as well

df['brand'] = df['brand'].fillna("Unknown")

In [17]:
df.isnull().sum()

index              0
product            0
category           0
sub_category       0
brand              0
sale_price         0
market_price       0
type               0
rating          8626
description      115
dtype: int64

In [18]:
# replace the null value of description with value of your choice

df['description']  = df['description'].fillna("Description not available")

In [19]:
df.isnull().sum()

index              0
product            0
category           0
sub_category       0
brand              0
sale_price         0
market_price       0
type               0
rating          8626
description        0
dtype: int64

In [20]:
df['rating'] = df.groupby(['brand','category','sub_category'])['rating'].transform(lambda x: x.fillna(x.mean))

In [21]:
df.isnull().sum()

index           0
product         0
category        0
sub_category    0
brand           0
sale_price      0
market_price    0
type            0
rating          0
description     0
dtype: int64

In [22]:
# explore the category column see how many category having
# which category has more products
# which category has least amount of products

df['category'].nunique()

11

In [23]:
df['category'].unique()

array(['Beauty & Hygiene', 'Kitchen, Garden & Pets',
       'Cleaning & Household', 'Gourmet & World Food',
       'Foodgrains, Oil & Masala', 'Snacks & Branded Foods', 'Beverages',
       'Bakery, Cakes & Dairy', 'Baby Care', 'Fruits & Vegetables',
       'Eggs, Meat & Fish'], dtype=object)

In [24]:
df['category'].value_counts()

category
Beauty & Hygiene            7867
Gourmet & World Food        4690
Kitchen, Garden & Pets      3580
Snacks & Branded Foods      2814
Foodgrains, Oil & Masala    2676
Cleaning & Household        2675
Beverages                    884
Bakery, Cakes & Dairy        851
Baby Care                    610
Fruits & Vegetables          557
Eggs, Meat & Fish            350
Name: count, dtype: int64

In [25]:
df.describe() # give statistical summary of the numerical columns

              index    sale_price  market_price
count  27554.000000  27554.000000  27554.000000
mean   13777.978733    322.519254    382.061820
std     7954.731236    486.271379    581.740644
min        1.000000      2.450000      3.000000
25%     6889.250000     95.000000    100.000000
50%    13777.500000    190.000000    220.000000
75%    20666.750000    359.000000    425.000000
max    27555.000000  12500.000000  12500.000000

In [27]:
df.describe(include = 'O') # includes all the objects type columns

,product,category,sub_category,brand,type,rating,description
count,27554,27554,27554,27554,27554,27554.0,27554
unique,23540,11,90,2314,426,1799.0,21944
top,Turmeric Powder/Arisina Pudi,Beauty & Hygiene,Skin Care,Fresho,Face Care,4.2,Description not available
freq,26,7867,2294,638,1508,2250.0,115

In [ ]:
# dropna - it is used only to drop null values
# pop - used with basic data types

In [28]:
df.drop(['index'], axis =1, inplace = True) # df.drop(columns=[col])

# axis = 1 for columns
# axis = 0 for rows

In [29]:
df.head()

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [35]:
df.drop(['product'], axis =1, inplace=True) # inplace =True

In [36]:
df.head()

,category,sub_category,brand,sale_price,mrp,type,rating,description,discount
0,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...,0.0
1,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ...",0.0
2,Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m...",131.0
3,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...,27.0
4,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...,0.0

In [38]:
df['discount'] = df['mrp'] - df['sale_price']

In [39]:
df.head()

,category,sub_category,brand,sale_price,mrp,type,rating,description,discount
0,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...,0.0
1,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ...",0.0
2,Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m...",131.0
3,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...,27.0
4,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...,0.0

In [46]:
# rename market_price and sales_price

df = df.rename(columns={'sale_price':"selling_price",'market_price':"mrp"})

In [47]:
df.head()

,category,sub_category,brand,selling_price,mrp,type,rating,description,discount
0,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...,0.0
1,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ...",0.0
2,Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m...",131.0
3,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...,27.0
4,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...,0.0

In [48]:
df.to_csv("Updated_EDA_file.csv")

In [49]:
print(df.groupby('category')['sub_category'].unique())

category
Baby Care                   [Baby Bath & Hygiene, Diapers & Wipes, Baby Fo...
Bakery, Cakes & Dairy       [Cookies, Rusk & Khari, Dairy, Breads & Buns, ...
Beauty & Hygiene            [Hair Care, Bath & Hand Wash, Skin Care, Fragr...
Beverages                   [Fruit Juices & Drinks, Tea, Energy & Soft Dri...
Cleaning & Household        [Pooja Needs, Bins & Bathroom Ware, All Purpos...
Eggs, Meat & Fish           [Fish & Seafood, Sausages, Bacon & Salami, Egg...
Foodgrains, Oil & Masala    [Dry Fruits, Masalas & Spices, Organic Staples...
Fruits & Vegetables         [Cuts & Sprouts, Fresh Fruits, Fresh Vegetable...
Gourmet & World Food        [Cooking & Baking Needs, Chocolates & Biscuits...
Kitchen, Garden & Pets      [Storage & Accessories, Kitchen Accessories, F...
Snacks & Branded Foods      [Breakfast Cereals, Frozen Veggies & Snacks, C...
Name: sub_category, dtype: object